//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WooDesign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personeller
    {
        public int PersonellerID { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public string Telefon { get; set; }
        public string Adres { get; set; }
        public string Email { get; set; }
        public string Cinsiyet { get; set; }
        public string MedeniHali { get; set; }
        public string DogumYeri { get; set; }
        public System.DateTime DogumTarihi { get; set; }
        public System.DateTime IseGirisTarihi { get; set; }
        public Nullable<int> YetkiID { get; set; }
    
        public virtual Yetkiler Yetkiler { get; set; }
    }
}
