//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WooDesign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UyeAdresleri
    {
        public int UyeAdresleriID { get; set; }
        public int UyeID { get; set; }
        public string Adres { get; set; }
    
        public virtual Uyeler Uyeler { get; set; }
    }
}
