//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WooDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class indirimler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public indirimler()
        {
            this.SiparisDetaylar = new HashSet<SiparisDetaylar>();
        }
    
        public int indirimlerID { get; set; }
        public string indirimTurAdi { get; set; }
        public string indirimFiyatSekli { get; set; }
        public Nullable<System.DateTime> BaslamaTarihi { get; set; }
        public Nullable<System.DateTime> BitisTarihi { get; set; }
        public Nullable<decimal> indirimMiktari { get; set; }
        public Nullable<bool> Durumu { get; set; }
        public string Aciklama { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisDetaylar> SiparisDetaylar { get; set; }
    }
}
