//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WooDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reklamlar
    {
        public int ReklamID { get; set; }
        public string ReklamAciklama { get; set; }
        public Nullable<System.DateTime> ReklamBaslangicTarihi { get; set; }
        public Nullable<System.DateTime> ReklamBitisTarihi { get; set; }
        public string Resim1 { get; set; }
        public string Resim2 { get; set; }
        public string Resim3 { get; set; }
    }
}
