//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WooDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunStoklari
    {
        public int UrunStoklariID { get; set; }
        public int UrunID { get; set; }
        public System.DateTime BaslangicTarih { get; set; }
        public System.DateTime BitisTarihi { get; set; }
        public int StokMiktari { get; set; }
        public int KalanUrun { get; set; }
        public string Aciklama { get; set; }
    
        public virtual Urunler Urunler { get; set; }
    }
}
